// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesExample.Persistence;

#nullable disable

namespace RazorPagesExample.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230915132107_InitialCreated")]
    partial class InitialCreated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.22");

            modelBuilder.Entity("RazorPagesExample.Persistence.Entities.Pet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Age = 4,
                            Name = "Fluffy",
                            Type = 1,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Age = 3,
                            Name = "Rover",
                            Type = 2,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Age = 1,
                            Name = "Whiskers",
                            Type = 1,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Age = 6,
                            Name = "Fido",
                            Type = 2,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            Age = 3,
                            Name = "Mittens",
                            Type = 1,
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("RazorPagesExample.Persistence.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Created = new DateTime(2023, 9, 15, 15, 21, 7, 242, DateTimeKind.Local).AddTicks(9835),
                            DateOfBirth = new DateTime(1989, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marci@example.com",
                            Name = "marci",
                            Password = "marci"
                        },
                        new
                        {
                            Id = 2L,
                            Created = new DateTime(2023, 9, 15, 15, 21, 7, 242, DateTimeKind.Local).AddTicks(9886),
                            DateOfBirth = new DateTime(1967, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@example.com",
                            Name = "John",
                            Password = "john"
                        },
                        new
                        {
                            Id = 3L,
                            Created = new DateTime(2023, 9, 15, 15, 21, 7, 242, DateTimeKind.Local).AddTicks(9889),
                            DateOfBirth = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice@example.com",
                            Name = "Alice",
                            Password = "alice"
                        },
                        new
                        {
                            Id = 4L,
                            Created = new DateTime(2023, 9, 15, 15, 21, 7, 242, DateTimeKind.Local).AddTicks(9891),
                            DateOfBirth = new DateTime(1985, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eve@example.com",
                            Name = "Eve",
                            Password = "eve"
                        },
                        new
                        {
                            Id = 5L,
                            Created = new DateTime(2023, 9, 15, 15, 21, 7, 242, DateTimeKind.Local).AddTicks(9894),
                            DateOfBirth = new DateTime(1992, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "grace@example.com",
                            Name = "Grace",
                            Password = "grace"
                        });
                });

            modelBuilder.Entity("RazorPagesExample.Persistence.Entities.Pet", b =>
                {
                    b.HasOne("RazorPagesExample.Persistence.Entities.User", "User")
                        .WithMany("Pets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Pet_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RazorPagesExample.Persistence.Entities.User", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
